// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChLc4zsHirk-pvX7kZFGj0xzlJ5xzyuAI',
    appId: '1:364784753740:web:fdaed57e2d15cca4c868e9',
    messagingSenderId: '364784753740',
    projectId: 'emergency-app-f8b54',
    authDomain: 'emergency-app-f8b54.firebaseapp.com',
    storageBucket: 'emergency-app-f8b54.appspot.com',
    measurementId: 'G-TP5SZCDZDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAveNaHU5nMPHFTuVLQTVZEOKI2DqvFj8Q',
    appId: '1:364784753740:android:746ef7015ac2075dc868e9',
    messagingSenderId: '364784753740',
    projectId: 'emergency-app-f8b54',
    storageBucket: 'emergency-app-f8b54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANTUdQkHpXPKfznwN7YTniQwZGZW_WF7A',
    appId: '1:364784753740:ios:47c23b453c5e9a68c868e9',
    messagingSenderId: '364784753740',
    projectId: 'emergency-app-f8b54',
    storageBucket: 'emergency-app-f8b54.appspot.com',
    iosClientId: '364784753740-n9q63rru8g90ng8p4h9bhd74p7n6f3eg.apps.googleusercontent.com',
    iosBundleId: 'com.example.emergencyapp',
  );
}
